name = 'gymrol-backend'
main = "src/index.ts"
compatibility_date = "2024-02-27"

[[d1_databases]]
binding = "GYMROL_DATABASE"
database_name = "gymrol-database"
database_id = "22a1442c-64be-466b-917c-02e3a19c5d9c"
migrations_dir = "drizzle/migrations"

[vars]
JWT_SECRET = "supersecretjwtkey"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_CLIENT_ID"
RESEND_API_KEY = "YOUR_RESEND_API_KEY" # For sending emails
RESEND_EMAIL_FROM = "no-reply@gymrol.com"
